# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e42c4febb9d79f83f8361e2337c99f3baae7eb1f6e9641a2eee08ea1f5712bfb6dc0f77e096f61d0036556a1e8bca28d55b57f8ae0f697dac18f75ef3debaae5

test:
  secret_key_base: c70dd69c850ce9cac2d413fa71a148ad2647a0bcae4aeb6e7fd5c24bc591e626d50e08cf3867d6264d8051a1362256f0a21461e7594fee5d506aaafa7ea56648

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
